### ISSUE TITLE
KL(p, q) equation mismatch

### ISSUE THREAD

**Issue by hossfard** [mlvu/worksheets#4]
In [Worksheet 5](https://github.com/mlvu/worksheets/blob/4fecbc1993280a41e1f556932b9fe3b6ed3d07a6/Worksheet%205%2C%20Pytorch.ipynb), the `kl_loss` is defined as

```py
kl = 0.5 * torch.sum(zsig.exp() - zsig + zmean.pow(2) - 1, dim=1)
```

Instead, I expect that the $\text{KL}(q(z|x), \mathcal{N}(0,I) )$ here should take the form

```py
kl = 0.5 * torch.sum(-zsig.log() + zsig + zmean.pow(2) - 1, dim=1)
```

Is this a mistake, am I mistaken, or is there perhaps a reason for changing the divergence term?

**Comment by pbloem** [comment]
It looks like it depends on what zsig represents. I think that in my implementation it's the logarithm of the variance, so that `zsig.exp()` is the variance and `zsig` is its logarithm.

If, in your version, `zsig` is the actual variance, then the two functions are equivalent. You just have to swap the first two terms inside the sum. 

Note that in your version you should apply an activation function to `zsig` to make sure it's positive. If you use `exp()`, then you're basically back to my version. You could also do `abs()` or softplus. 

This is from a first look at just your message. Let me know if that explains it. If not, I can have a closer look at the code.

**Comment by hossfard** [comment]
Thanks for the explanation. I had assumed that `zsig` was the variance.
